name: easy_dialogs
description: Easy to use dialogs with lists
version: 1.1.0
author: Figen Güngör <figengungor1@gmail.com>
homepage: https://github.com/figengungor/easy_dialogs

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
